name: bioacoustics-web-app
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and core
  - python=3.10
  - pip
  
  # Data processing and scientific computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - polars>=0.20.0
  
  # Audio processing
  - librosa>=0.10.0
  - soundfile>=0.12.0
  - audioread>=3.0.0
  - ffmpeg
  
  # Machine learning
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  
  # Web framework and utilities
  - requests>=2.31.0
  
  # Node.js for React frontend (platform dependent)
  - nodejs>=18
  
  # pip dependencies (packages better installed via pip)
  - pip:
    # Machine learning frameworks
    - tensorflow>=2.13.0,<2.20.0
    - tensorflow-hub>=0.14.0
    
    # Web framework
    - fastapi>=0.104.0,<0.110.0
    - uvicorn[standard]>=0.24.0
    - python-multipart>=0.0.6
    - pydantic>=2.5.0,<3.0.0
    
    # Additional audio processing
    - soxr>=0.3.0
    
    # Development and testing (optional)
    - pytest>=7.0.0
    - black>=23.0.0
    - flake8>=6.0.0