from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_health_check():
    """
    Basic smoke test to verify the API is responsive.
    Note: Since we haven't implemented a dedicated /health endpoint yet,
    we'll check the root endpoint or a documentation endpoint.
    """
    # Checking /docs as a proxy for app health since it's auto-generated by FastAPI
    response = client.get("/docs")
    assert response.status_code == 200
