import os
BACKEND = os.environ.get("BACKEND", "PERCH")
#BACKEND = "PERCH_IGNORE_SR"

if BACKEND == "PERCH":
    TARGET_SR = 32000
    MODEL_SR = 32000
    MODEL_CONTEXT_FRAME = 160000
    WINDOW = MODEL_CONTEXT_FRAME / TARGET_SR
    HOP_SIZE = MODEL_CONTEXT_FRAME
    PERCH_V = 8
    MIN_FREQ = 60
    MAX_FREQ = 10000
    
if BACKEND == "PERCH_IGNORE_SR":
    TARGET_SR = 384000
    MODEL_SR = 32000
    MODEL_CONTEXT_FRAME = 160000
    WINDOW = MODEL_CONTEXT_FRAME / TARGET_SR
    HOP_SIZE = MODEL_CONTEXT_FRAME
    PERCH_V = 8
    MIN_FREQ = 60
    MAX_FREQ = 10000

if BACKEND == "BirdNET_2.4":
    TARGET_SR = 48000
    MODEL_SR = 48000
    MODEL_CONTEXT_FRAME = 144000
    WINDOW = MODEL_CONTEXT_FRAME / TARGET_SR
    HOP_SIZE = MODEL_CONTEXT_FRAME
    MIN_FREQ = 150
    MAX_FREQ = 15000
    MODEL_PATH = 'embedding_checkpoints/V2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite'
    TFLITE_THREADS = 1
    #PERCH_V = None

if BACKEND == "PNWCnet":
    TARGET_SR = 32000
    MODEL_SR = 32000
    MODEL_CONTEXT_FRAME = 384000
    WINDOW = MODEL_CONTEXT_FRAME / TARGET_SR
    HOP_SIZE = MODEL_CONTEXT_FRAME
    MIN_FREQ = 0
    MAX_FREQ = 4000

if BACKEND == "PNWCnet_EXPANDED":
    TARGET_SR = 32000
    MODEL_SR = 32000
    MODEL_CONTEXT_FRAME = 384000
    WINDOW = MODEL_CONTEXT_FRAME / TARGET_SR
    HOP_SIZE = MODEL_CONTEXT_FRAME
    MIN_FREQ = 0
    MAX_FREQ = 12000